config/routes.rb
QtmvcRails::Application.routes.draw do

  resources :relationships, :only => [:create, :destroy]
  resources :groups, :except => [:show, :destroy] do
    resources :students, :controller => :relationships
  end

  root :to => 'groups#index'

end

app/models/course.rb
class Course < ActiveRecord::Base
  attr_accessible :name
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  attr_accessible :fio

  belongs_to :organization
  has_many :relationships,
           :dependent => :destroy
  has_many :groups, :through => :relationships

  validates :fio, :presence => true, :length => { :minimum => 6 }

  def in_group?(group)
    relationships.find_by_group_id(group.id)
  end
end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :name, :course_id, :instructor_id

  belongs_to :instructor
  belongs_to :course

  has_many :relationships,
           :dependent => :destroy
  has_many :students,
           :through => :relationships, :source => :employee

  validates :instructor_id, :presence => true
  validates :course_id, :presence => true
  validates :name, :presence => true

  def add(student)
    relationships.create!(:employee_id => student)
  end

  def remove(student)
    relationships.find_by_employee_id(student).destroy
  end
end

app/models/instructor.rb
class Instructor < ActiveRecord::Base
  attr_accessible :fio, :email

  has_many :organizations
  has_many :groups
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  attr_accessible :name, :inn

  belongs_to :instructor
  has_many :employees

  inn_regex = /\d[10]/
  validates :name, :presence => true
  validates :inn, :presence => true, :length => { :is => 10 }, :format => { :with => inn_regex }

  #TODO: Select employees that not in current group
  def employees_select_by(group)
    employees
  end
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  attr_accessible :employee_id

  belongs_to :employee
  belongs_to :group

  validates :group_id, :presence => true
  validates :employee_id, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :set_initial_breadcrumbs

  private

  def set_initial_breadcrumbs
    add_breadcrumb "Home", :root_path
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  add_breadcrumb 'Create a new group', '', :only => [:new, :create]
  add_breadcrumb 'Edit a group', '', :only => [:edit, :update]

  def index
    @title = "Group list"
    @groups = Group.all
  end

  def new
    @title = "New group"
    @group = Group.new
    @instructors = Instructor.all
  end

  def edit
    @title = "Edit group"
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update_attributes(params[:group])
      flash[:success] = "Group updated"
      redirect_to groups_path
    else
      @title = "Edit group"
      render 'edit'
    end
  end

  def create
    @group = Group.new(params[:group].merge(:course_id => 1))
    if @group.save
      flash[:success] = 'Group created'
      redirect_to edit_group_path @group
    else
      @title = "New"
      @instructors = Instructor.all
      render 'new'
    end
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  add_breadcrumb 'Group list', :groups_path, :only => [:new]
  add_breadcrumb 'Add student', '', :only => [:new]

  def new
    @group = Group.find_by_id(params[:group_id])
    @relationship = @group.relationships.new
  end

  def create
    @group = Group.find(params[:relationship][:group_id])
    @relationship = @group.relationships.build(:employee_id => params[:relationship][:employee_id])
    if @relationship.save
      flash[:success] = "Successfully added to group"
      redirect_to edit_group_path(@group)
    else
      #TODO: It should not render /relationships URL
      render 'new'
    end
  end

  def destroy
    @group = Group.find(params[:group_id])
    @employee = Employee.find(params[:id])
    @group.remove(@employee)
    redirect_to edit_group_path(@group)
  end

  def show
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    base_title = "Managing Study groups"
    "#{base_title} | #{@title}"
  end

  def logo
    image_tag("rails.png", :alt => "Logo", :class => "round")
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/employees/_employee.html.erb
<tr>
  <td><%= employee.fio %></td>
  <td><%= employee.organization.name %></td>
  <td><%= link_to "delete", group_student_path(@group, employee), :method => :delete %></td>
</tr>

app/views/groups/_fields.html.erb
<%= render 'shared/error_messages', :object => f.object %>
<div class="field">
  <%= f.label :instructor_id %><br />
  <%= f.collection_select :instructor_id, @instructors, :id, :fio %>
</div>
<div class="field">
  <%= f.label :name %><br />
  <%= f.text_field :name %>
</div>

app/views/groups/_group.html.erb
<tr>
  <td><%= group.name %></td>
  <td><%= group.instructor.fio %></td>
  <td><%= group.students.length %></td>
  <td><%= link_to "edit", edit_group_path(group) %></td>
</tr>

app/views/groups/edit.html.erb
<h1>Редактировать учебную группу</h1>
<%= form_for @group do |f| %>
    <div class="field">
      <%= f.label :instructor, "Преподаватель: " %>
      <%= f.label :instructor_id, @group.instructor.fio %>
    </div>
    <div class="field">
      <%= f.label :name, "Название учебной группы" %><br />
      <%= f.text_field :name %>
    </div>
    <div class="actions">
      <%= f.submit "Save changes" %>
    </div>
<% end %>
<table summary="Students table">
  <tr>
    <th>Сотрудник</th>
    <th>Организация</th>
    <th></th>
  </tr>
  <%= render @group.students %>
</table>
<%= button_to "Add to group", new_group_student_path(@group.id), :method => :get %>

app/views/groups/index.html.erb
<h1>Список учебных групп</h1>
<div class="groups">
  <table summary="Group table">
    <tr>
      <th>Название</th>
      <th>Преподаватель</th>
      <th>Количество студентов</th>
      <th></th>
    </tr>
    <%= render @groups %>
  </table>
  <%= button_to "Создать учебную групппу", new_group_path, :method => :get %>
</div>

app/views/groups/new.html.erb
<h1>Создать учебную группу</h1>
<%= form_for(@group) do |f| %>
    <%= render 'fields', :f => f %>
    <div class="actions">
      <%= f.submit "Создать учебную группу" %>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><a href="#">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to logo, root_path %>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", "#" %></li>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag    'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag    'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag    'application' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= render 'layouts/stylesheets' %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class='round'>
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, :class => "flash #{key}") %>
        <% end %>
        <%= breadcrumbs %>
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
</body>
</html>

app/views/relationships/destroy.html.erb
<h1>Temp</h1>

app/views/relationships/new.html.erb
<h1>Добавить сотрудника в учебную группу</h1>
<%= form_for @relationship do |f| %>
    <%= render 'shared/error_messages', :object => f.object %>
    <div class="field">
      Название группы:
      <%= f.hidden_field :group_id %>
      <%= f.label :group_id, @group.name %>
    </div>
    <div class="field">
      Преподаватель:
      <%= f.label :instructor_fio, @group.instructor.fio %>
    </div>
    <div class="field">
      <%= f.label "org_id", "Организация" %><br />
      <%= collection_select :organization, :id, Organization.order(:name),
                            :id, :name, :include_blank => true  %>
    </div>
    <div class="field">
      <%= f.label :employee_id, "Сотрудник" %><br />
      <%= f.grouped_collection_select :employee_id, Organization.order(:name),
                                      :employees, :name, :id, :fio, :include_blank => true %>
    </div>
    <div class="actions">
      <%= f.submit "Добавить" %>
    </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %>
        prohibited this <%= object.class.to_s.underscore.humanize.downcase %>
        from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>